# Generated by Django 3.0.7 on 2020-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='choice',
            field=models.CharField(max_length=32),
        ),
    ]
