# Generated by Django 3.0.7 on 2020-06-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200625_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='budget',
            field=models.IntegerField(default=20),
        ),
    ]
